name: "PlayStation Changeinfo"
description: "Transform CHANGELOG.md into changeinfo.xml "
author: "Applelo"
branding:
  color: blue
  icon: git-pull-request
inputs:
  # Main
  input:
    description: "The path of the changelog markdown file"
    default: "CHANGELOG.md"
    required: false
  output:
    description: "The path of the changeinfo xml file"
    default: "sce_sys/changeinfo.xml"
    required: false
  branch:
    description: "The name of the branch for the pull request"
    default: "ps-changeinfo"
    required: false
  token:
    description: "GitHub token"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
